version: "3.9"

services:
  backend:
    build: ./backend
    container_name: coupe-backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8000:8000"

  frontend-admin:
    build: ./frontend-admin
    container_name: coupe-frontend-admin
    restart: always
    env_file:
      - ./frontend-admin/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend-public:
    build: ./frontend-public
    container_name: coupe-frontend-public
    restart: always
    env_file:
      - ./frontend-public/.env.production
    ports:
      - "3100:3000"
    depends_on:
      - backend

volumes:
  sqlite_data:
