tls:
  certificates:
    - certFile: /certs/coupedeluniversite.pem
      keyFile: /certs/coupedeluniversite.key
  
  stores:
    default:
      defaultCertificate:
        certFile: /certs/coupedeluniversite.pem
        keyFile: /certs/coupedeluniversite.key

  options:
    default:
      minVersion: VersionTLS12
      # On retire les cipherSuites manuels pour éviter les erreurs de frappe
      # Traefik utilisera ses valeurs sécurisées par défaut

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true